### ISSUE TITLE
potentially harmful notation

### ISSUE THREAD

**Issue by nhcho91** [JinraeKim/FlightSims.jl#122]
p as argument of dynamics function overlaps with p as the first subset of state vector

https://github.com/JinraeKim/FlightSims.jl/blob/8ae93b0030ac73d8c36fbcc0f44d91760f86cf95/src/environments/integrated_environments/backstepping_position_controller_static_allocator_multicopter_env.jl#L30-L38

**Comment by JinraeKim** [comment]
Thanks :)
I'll fix it.
