### ISSUE TITLE
Add a new API `Params` for simulation parameter setting

### ISSUE THREAD

**Issue by JinraeKim** [JinraeKim/FlightSims.jl#44]
Add a new API `Params` for generating parameter settings for simulations.
It is necessary to consider multiple scenarios with various parameter settings (especially for changing controller gains).

**Comment by JinraeKim** [comment]
@hnlee77 
Do you have any ideas for this?
For example, what's the desired form of `LinearSystemEnv`?

1) `LinearSystemEnv(A, B, Q, R)` and no parameters (we cannot change the matrices).
2) `LinearSystemEnv(n, m)` and `Params(env::LinearSystemEnv)(A, B, Q, R)` (then, we can change the matrices `A`, ..., `R`).
3) `LinearSystemEnv()` and `Params(env::LinearSystemEnv)(A, B, Q, R)` (then, it would be hard to set the default values of  "State(env::LinearSystemEnv)")

**Comment by JinraeKim** [comment]
An alternative way is that not to force users to use a new API `Params`.
In this case, it may be hard to change some parameters if the struct is defined as an immutable struct.

**Comment by hnlee77** [comment]
In the first form, ```LinearSystemEnv(A, B, Q, R)``` , still we can change the matrices?
Maybe, it would be in the ```initialise()``` that we want to change the parameters...

**Comment by JinraeKim** [comment]
> In the first form, `LinearSystemEnv(A, B, Q, R)` , still we can change the matrices?

"If" the environment struct is defined as a "mutable" struct.
IMO, mutable structs are not good in practice for solid type and value assignment when handling structs.



> Maybe, it would be in the `initialise()` that we want to change the parameters...

Also, `initialise()` methods may consume the memory undesirably much (and hard to update parameters within a scenario).
